server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://121.175.150.249:3306/team2?serverTimezone=Asia/Seoul
    username: team2
    password: toor
    
mybatis:
  mapper-locations:
  - /mappers/*.xml








