server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://121.175.150.249:3306/team2?serverTimezone=Asia/Seoul
    username: team2
    password: toor
    
  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 296942560434-n4evelrfh2qft4uk68otetk5krfpnejb.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          facebook:
            client-id: 611789176901817
            client-secret: 762d3b30170998212e8734cee6e77b8f
            scope:
            - email
            - public_profile
          naver:
            client-id: 6t0QJkD3VADsJ11Dz1DO
            client-secret: 6nseh4a8Dr
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 가지고 올때 response라는 key값으로 데이터를 전달해 준다.

mybatis:
  mapper-locations:
  - /mappers/*.xml







