server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8001/movie_project?useUnicode=true
    username: root
    password: toor
    
  security:
    user:
      name: test
      password: 1234   
    
mybatis:
  mapper-locations:
  - /mappers/*.xml








